"""add ingest metadata tables

Revision ID: de4b46fabff2
Revises: 
Create Date: 2026-02-15 20:49:10.198747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'de4b46fabff2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_version_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('pipeline_status', sa.String(length=16), nullable=False),
    sa.Column('action_taken', sa.String(length=16), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('checks_total', sa.Integer(), nullable=False),
    sa.Column('checks_passed', sa.Integer(), nullable=False),
    sa.Column('checks_failed', sa.Integer(), nullable=False),
    sa.Column('failed_checks', sa.JSON(), nullable=False),
    sa.Column('tables_received', sa.JSON(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('experiment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('ingested_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('total_batches', sa.Integer(), nullable=False),
    sa.Column('records', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'table_name', 'batch_id', name='uq_ingested_batch_key')
    )
    op.create_index(op.f('ix_ingested_batches_table_name'), 'ingested_batches', ['table_name'], unique=False)
    op.create_index(op.f('ix_ingested_batches_version'), 'ingested_batches', ['version'], unique=False)
    op.create_table('model_registry_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('trained_on', sa.String(length=64), nullable=False),
    sa.Column('features_count', sa.Integer(), nullable=False),
    sa.Column('train_metrics', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_status_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('pipeline_status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_status_states')
    op.drop_table('model_registry_states')
    op.drop_index(op.f('ix_ingested_batches_version'), table_name='ingested_batches')
    op.drop_index(op.f('ix_ingested_batches_table_name'), table_name='ingested_batches')
    op.drop_table('ingested_batches')
    op.drop_table('experiment_logs')
    op.drop_table('data_version_states')
    # ### end Alembic commands ###
